### ISSUE TITLE
Is there any way to turn off SSE stream data logging

### ISSUE THREAD

**Issue by vongohren** [harness/ff-java-server-sdk#169]
This line fills our logs and I dont see why its needed. Why cant we turn it of by config?

https://github.com/harness/ff-java-server-sdk/blob/db0661f4631ed5bdc5dc517e4495bdc4ffa14e64/src/main/java/io/harness/cf/client/connector/EventSource.java#L182

**Comment by andybharness** [comment]
Hi @vongohren 
This has been dropped to `debug` level for 1.4.x, see https://github.com/harness/ff-java-server-sdk/pull/170

Thanks
