### ISSUE TITLE
Metrics are not flushed when the client is closed

### ISSUE THREAD

**Issue by youngm** [harness/ff-java-server-sdk#202]
It would be nice if the client attempted to flush its metrics queue on `close()`. That would help make analytics a bit more accurate.

**Comment by erdirowlands** [comment]
Hi @youngm, this is a great suggestion and it's something that we wish we added to the SDKs from day 1. 

The behaviour where we do not flush metrics on close is consistent with the majority of our SDKs and we would add this on a case by case basis, but have no plans to generally speaking across the board. 

For Java specifically, I have reviewed the code and could feasibly introduce it in the same release for https://github.com/harness/ff-java-server-sdk/issues/201 so will aim for that.  :-) 

I'll keep you updated as I work on both issues.

**Comment by erdirowlands** [comment]
Hey @youngm we've been able to include this functionality in 1.8.0 which has just been released.  Please see https://github.com/harness/ff-java-server-sdk/releases/tag/1.8.0 for details.   Thank you!

Also please feel free to email support@harness.io with any other issues, on top of using GitHub, as we can typically get you triage from our support team.  

Have a great weekend!
